### ISSUE TITLE
main-server module path resolve issue

### ISSUE THREAD

**Issue by zhenyulin** [xygon/react-redux-typescript-dotnet-core#2]
hi @xygon , I'm currently getting a issue regarding the module resolve of the `main-server`, had a look into the webpack config, and it seems to be fine, can you point out a direction to fix this?

Are we using `boot-server.tx` to do the server side rendering or `dotnet core prerendering` for server-side rendering?

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Call to Node module failed with error: Prerendering failed because of error: Error: Cannot find module 'src/ReactRedux/ClientApp/dist/main-server'

**Comment by xygon** [comment]
I've just arrived in Scotland and can't look at this for a few hours (got to spend time with my kids on the beach!). I'll try to have a look tonight.

**Comment by zhenyulin** [comment]
@xygon I had some further inspection, it looks like in the html file the path is bound to `ClientApp/dist/main-server`, while in production mode, the file would be compiled to `wwwroot/dist/`, running in Development I'm currently getting the error of `Error: Cannot find module './wwwroot/dist/vendor-manifest.json'`

**Comment by zhenyulin** [comment]
morning @xygon, can you have a quick look into this today? It is kind of blocking me going further on evaluating this solution

**Comment by xygon** [comment]
I’m out all day today – in Scotland on holiday. I’ll try and have a look tonight.

**Comment by zhenyulin** [comment]
fixed here
https://github.com/xygon/react-redux-typescript-dotnet-core/pull/3/commits/2f671c4eaad5481193612560577be7eff35addaa
